// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZJ023z55vlAiD31ZvpgmCx2teEHflTU',
    appId: '1:330475462534:web:5b4b45dcd4ad8f4f2ad607',
    messagingSenderId: '330475462534',
    projectId: 'fir-crud-flutter-c61ca',
    authDomain: 'fir-crud-flutter-c61ca.firebaseapp.com',
    storageBucket: 'fir-crud-flutter-c61ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOPseytsdkm7rRI4L_SeZK_r6Qb22wXg',
    appId: '1:330475462534:android:f3e04f178e1a87462ad607',
    messagingSenderId: '330475462534',
    projectId: 'fir-crud-flutter-c61ca',
    storageBucket: 'fir-crud-flutter-c61ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlL7J7n7JApXLnhQOHWfNUSUGiI0eDIaA',
    appId: '1:330475462534:ios:20949b1baf92cb1d2ad607',
    messagingSenderId: '330475462534',
    projectId: 'fir-crud-flutter-c61ca',
    storageBucket: 'fir-crud-flutter-c61ca.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlL7J7n7JApXLnhQOHWfNUSUGiI0eDIaA',
    appId: '1:330475462534:ios:e141fc4883e15a4b2ad607',
    messagingSenderId: '330475462534',
    projectId: 'fir-crud-flutter-c61ca',
    storageBucket: 'fir-crud-flutter-c61ca.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
